### ISSUE TITLE
missing vbr_sample_ch8.bin

### ISSUE THREAD

**Issue by int3rsys** [bootkitsbook/bootkits#2]
Hello there,
I hope this is the right place to write about this issue. If not, I'm really sorry.
I'm in the middle of the exercises in chapter 8 and I cannot continue pass infected_mbr.bin. I feel like there are missing files, for example: vbr_sample_ch8.bin mentioned in page 106.

When I bought the book from https://www.humblebundle.com/, It didn't come with any additional files. Am I missing something?

Thanks!

**Comment by matrosov** [comment]
Thanks for feedback. I believe all the related files uploaded on github but it's can be naming confusion.

For bootkit chapters with infected MBR/VBR/IPL samples located in Bootkits folder with similar names. Exactly these samples are discussed in chapter 13 and also related to the following exercises.

Also, you can find all the droppers to prepare your own infected VM, but pay attention because some of them have simple tricks to detect the VM environment before starting the infection process.
